const { sequelize } = require('../db/sequelize'); // Ajuste le chemin si besoin

module.exports = async () => {
  try {
    // Utilisation du modèle evenement depuis sequelize.models
    await sequelize.models.Evenement.bulkCreate([
      {
        titre: 'Conférence sur l\'Innovation',
        description: 'Une conférence dédiée à l\'innovation technologique.',
        id_createur: 1, // Assurez-vous que cet ID existe dans la table Utilisateur
        id_lieu: 1, // Assurez-vous que cet ID existe dans la table Lieu
        date_debut: '2025-06-01 09:00:00',
        date_fin: '2025-06-01 17:00:00',
        places_initial: 50,
        places_disponible: 50,
        created: new Date(),
      },
      {
        titre: 'Festival de Musique',
        description: 'Un festival en plein air avec des concerts de musique.',
        id_createur: 2,
        id_lieu: 2,
        date_debut: '2025-06-15 18:00:00',
        date_fin: '2025-06-17 02:00:00',
        places_initial: 30,
        places_disponible: 30,
        created: new Date(),
      },
      {
        titre: 'Salon du Livre',
        description: 'Rencontres avec des auteurs et des éditeurs.',
        id_createur: 3,
        id_lieu: 3,
        date_debut: '2025-07-01 10:00:00',
        date_fin: '2025-07-01 18:00:00',
        places_initial: 40,
        places_disponible: 40,
        created: new Date(),
      },
      {
        titre: 'Exposition Art Contemporain',
        description: 'Exposition d\'art contemporain avec des artistes locaux.',
        id_createur: 4,
        id_lieu: 4,
        date_debut: '2025-07-10 11:00:00',
        date_fin: '2025-07-10 19:00:00',
        places_initial: 50,
        places_disponible: 50,
        created: new Date(),
      },
      {
        titre: 'Séminaire sur la Blockchain',
        description: 'Un séminaire pour explorer les applications de la blockchain.',
        id_createur: 5,
        id_lieu: 5,
        date_debut: '2025-08-05 09:00:00',
        date_fin: '2025-08-05 17:00:00',
        places_initial: 50,
        places_disponible: 50,
        created: new Date(),
      },
      {
        titre: 'Atelier de Développement Web',
        description: 'Un atelier pour apprendre les bases du développement web.',
        id_createur: 6,
        id_lieu: 6,
        date_debut: '2025-08-20 09:00:00',
        date_fin: '2025-08-20 16:00:00',
        places_initial: 50,
        places_disponible: 50,
        created: new Date(),
      },
      {
        titre: 'Festival de Cinéma',
        description: 'Projection de films indépendants et débats.',
        id_createur: 7,
        id_lieu: 7,
        date_debut: '2025-09-01 14:00:00',
        date_fin: '2025-09-05 23:00:00',
        places_initial: 50,
        places_disponible: 50,
        created: new Date(),
      },
      {
        titre: 'Compétition de Startups',
        description: 'Pitch de nouvelles startups devant des investisseurs.',
        id_createur: 8,
        id_lieu: 8,
        date_debut: '2025-09-10 08:30:00',
        date_fin: '2025-09-10 18:00:00',
        places_initial: 50,
        places_disponible: 50,
        created: new Date(),
      },
      {
        titre: 'Marché des Créateurs',
        description: 'Vente de créations artisanales et objets uniques.',
        id_createur: 9,
        id_lieu: 9,
        date_debut: '2025-09-20 10:00:00',
        date_fin: '2025-09-20 17:00:00',
        places_initial: 50,
        places_disponible: 50,
        created: new Date(),
      },
      {
        titre: 'Conférence sur la Transformation Digitale',
        description: 'La transformation digitale des entreprises et ses défis.',
        id_createur: 10,
        id_lieu: 10,
        date_debut: '2025-10-02 09:00:00',
        date_fin: '2025-10-02 17:00:00',
        places_initial: 50,
        places_disponible: 50,
        created: new Date(),
      },
      {
        titre: 'Forum de l\'Emploi',
        description: 'Un forum pour rencontrer des recruteurs et postuler.',
        id_createur: 11,
        id_lieu: 11,
        date_debut: '2025-10-10 10:00:00',
        date_fin: '2025-10-10 16:00:00',
        places_initial: 50,
        places_disponible: 50,
        created: new Date(),
      },
      {
        titre: 'Forum de l\'Entrepreneuriat',
        description: 'Un forum pour les entrepreneurs en quête de conseils.',
        id_createur: 12,
        id_lieu: 12,
        date_debut: '2025-10-15 08:30:00',
        date_fin: '2025-10-15 18:00:00',
        places_initial: 50,
        places_disponible: 50,
        created: new Date(),
      },
      {
        titre: 'Hackathon de Développeurs',
        description: 'Compétition pour développer des solutions innovantes.',
        id_createur: 13,
        id_lieu: 13,
        date_debut: '2025-11-01 10:00:00',
        date_fin: '2025-11-02 18:00:00',
        places_initial: 50,
        places_disponible: 50,
        created: new Date(),
      },
      {
        titre: 'Concert de Jazz',
        description: 'Concert de jazz en plein air.',
        id_createur: 14,
        id_lieu: 14,
        date_debut: '2025-11-10 20:00:00',
        date_fin: '2025-11-10 23:00:00',
        places_initial: 50,
        places_disponible: 50,
        created: new Date(),
      },
      {
        titre: 'Salon du Design',
        description: 'Salon pour découvrir les dernières tendances en design.',
        id_createur: 15,
        id_lieu: 15,
        date_debut: '2025-11-20 09:00:00',
        date_fin: '2025-11-20 18:00:00',
        places_initial: 50,
        places_disponible: 50,
        created: new Date(),
      },
    ]);
    console.log('✅ Événements insérés avec succès');
  } catch (error) {
    console.error('❌ Erreur lors de l\'insertion des événements :', error);
  }
};
