const { sequelize } = require('../db/sequelize'); // Assure-toi que sequelize est bien importé

module.exports = async () => {
  try {
    await sequelize.models.Utilisateur.bulkCreate([ 
      {
        nom: 'Alice Dupont',
        email: 'alice@example.com',
        mot_de_passe: 'hashedpassword1',
        role: 'admin',
        photo: 'https://example.com/photo1.jpg',
        telephone: '0123456789',
        bibliographie: 'Alice est une organisatrice d’événements passionnée par la culture.',
        created: new Date(),
      },
      {
        nom: 'Bob Martin',
        email: 'bob@example.com',
        mot_de_passe: 'hashedpassword2',
        role: 'user',
        photo: 'https://example.com/photo2.jpg',
        telephone: '0987654321',
        bibliographie: 'Bob est un participant régulier aux événements culturels.',
        created: new Date(),
      },
      {
        nom: 'Carla Lemoine',
        email: 'carla@example.com',
        mot_de_passe: 'hashedpassword3',
        role: 'organisateur',
        photo: 'https://example.com/photo3.jpg',
        telephone: '0147852369',
        bibliographie: 'Carla organise des événements musicaux dans la région.',
        created: new Date(),
      },
      {
        nom: 'David Robert',
        email: 'david@example.com',
        mot_de_passe: 'hashedpassword4',
        role: 'user',
        photo: 'https://example.com/photo4.jpg',
        telephone: '0612345678',
        bibliographie: 'David est un passionné de cinéma.',
        created: new Date(),
      },
      {
        nom: 'Eva Dumont',
        email: 'eva@example.com',
        mot_de_passe: 'hashedpassword5',
        role: 'organisateur',
        photo: 'https://example.com/photo5.jpg',
        telephone: '0623456789',
        bibliographie: 'Eva est responsable d’événements littéraires.',
        created: new Date(),
      },
      {
        nom: 'Frank Lefevre',
        email: 'frank@example.com',
        mot_de_passe: 'hashedpassword6',
        role: 'admin',
        photo: 'https://example.com/photo6.jpg',
        telephone: '0752345678',
        bibliographie: 'Frank est un administrateur de festivals de musique.',
        created: new Date(),
      },
      {
        nom: 'Gina Moreau',
        email: 'gina@example.com',
        mot_de_passe: 'hashedpassword7',
        role: 'user',
        photo: 'https://example.com/photo7.jpg',
        telephone: '0634567890',
        bibliographie: 'Gina adore participer à des événements gastronomiques.',
        created: new Date(),
      },
      {
        nom: 'Hugo Leroy',
        email: 'hugo@example.com',
        mot_de_passe: 'hashedpassword8',
        role: 'organisateur',
        photo: 'https://example.com/photo8.jpg',
        telephone: '0712345678',
        bibliographie: 'Hugo organise des salons professionnels.',
        created: new Date(),
      },
      {
        nom: 'Isabelle Bernard',
        email: 'isabelle@example.com',
        mot_de_passe: 'hashedpassword9',
        role: 'user',
        photo: 'https://example.com/photo9.jpg',
        telephone: '0723456789',
        bibliographie: 'Isabelle est une passionnée de danse et participe à de nombreux événements.',
        created: new Date(),
      },
      {
        nom: 'Jacques Fournier',
        email: 'jacques@example.com',
        mot_de_passe: 'hashedpassword10',
        role: 'admin',
        photo: 'https://example.com/photo10.jpg',
        telephone: '0734567890',
        bibliographie: 'Jacques est un organisateur d’événements artistiques.',
        created: new Date(),
      },
      {
        nom: 'Klara Joly',
        email: 'klara@example.com',
        mot_de_passe: 'hashedpassword11',
        role: 'user',
        photo: 'https://example.com/photo11.jpg',
        telephone: '0745678901',
        bibliographie: 'Klara est une actrice de théâtre passionnée.',
        created: new Date(),
      },
      {
        nom: 'Louis Dupuis',
        email: 'louis@example.com',
        mot_de_passe: 'hashedpassword12',
        role: 'organisateur',
        photo: 'https://example.com/photo12.jpg',
        telephone: '0756789012',
        bibliographie: 'Louis est spécialisé dans la gestion d’événements sportifs.',
        created: new Date(),
      },
      {
        nom: 'Monique Petit',
        email: 'monique@example.com',
        mot_de_passe: 'hashedpassword13',
        role: 'user',
        photo: 'https://example.com/photo13.jpg',
        telephone: '0767890123',
        bibliographie: 'Monique aime participer à des événements culinaires.',
        created: new Date(),
      },
      {
        nom: 'Nicolas Lemoine',
        email: 'nicolas@example.com',
        mot_de_passe: 'hashedpassword14',
        role: 'organisateur',
        photo: 'https://example.com/photo14.jpg',
        telephone: '0778901234',
        bibliographie: 'Nicolas est un organisateur de conférences scientifiques.',
        created: new Date(),
      },
      {
        nom: 'Olivia Dupuis',
        email: 'olivia@example.com',
        mot_de_passe: 'hashedpassword15',
        role: 'user',
        photo: 'https://example.com/photo15.jpg',
        telephone: '0789012345',
        bibliographie: 'Olivia adore assister à des événements de mode.',
        created: new Date(),
      },
    ]);
  } catch (error) {
    console.error('❌ Erreur lors du seed des utilisateurs :', error);
  }
};
